### ISSUE TITLE
缺少脚本文件

### ISSUE THREAD

**Issue by TGLTommy** [Xt-cyh/CoDI-Eval#1]
你好，非常感谢开源共享👍🏻👍🏻👍🏻 在 utils/ 文件夹下，缺少了脚本文件: query_huggingface.py ，麻烦上传一下。

**Comment by Xt-cyh** [comment]
感谢您的提醒，目前已经上传了该脚本文件。不过该脚本文件实际上在最终的代码中并未真正使用，只是代码中import的部分没能彻底删除。

**Comment by TGLTommy** [comment]
> 感谢您的提醒，目前已经上传了该脚本文件。不过该脚本文件实际上在最终的代码中并未真正使用，只是代码中import的部分没能彻底删除。

好的，谢谢哈，目前正在研究你的项目，很有启发，谢谢哈
