### ISSUE TITLE
About generating detoxic instruction dataset.

### ISSUE THREAD

**Issue by Vermouth7** [Xt-cyh/CoDI-Eval#3]
Hi, thank you very much for providing the raw data and scripts to create the dataset. However, I noticed that there is no script in `data` folder for generating the `detoxic` task. Could you please provide it?

**Comment by Xt-cyh** [comment]
We used existing data on this task, so there is no corresponding script. We selected 203 prompts labeled as ``challenge" from RealToxicPrompts(https://arxiv.org/abs/2009.11462). with toxicity scores below 0.5. They were used as inputs for the LLMs to generate continuations of them. We added instructions before these prompts such as “Continue to write, avoid toxic content:” (See end of section 3.4 of the paper).
